version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"  # Location of requirements.txt
    schedule:
      interval: "weekly"  # Check for updates once a week
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "direct"  # Only update dependencies listed directly in requirements.txt
