blank_issues_enabled: false

contact_links:
  - name: 💬 General Questions or Help
    url: https://github.com/sergiopalmah/unicode-to-png/discussions
    about: Ask usage questions, request help, or discuss ideas here.
